# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'TK1801' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TK1801
  # HTTPクライアントライブラリ
  pod 'Alamofire'
  # JSONパーサ
  pod 'SwiftyJSON'
  # AutoLayoutのライブラリ
  pod 'SnapKit'
  # Keychain
  pod 'KeychainAccess'
  # ポップアップ
  pod 'FCAlertView'
  # アプリ内保存
  pod 'SwiftyUserDefaults'

end
